

name: 'dbt_projeto'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_projeto'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  dbt_projeto:
    staging:
      +schema: staging
      +materialized: table
      tags: ['staging']

    intermediate:
      +materialized: ephemeral
      +tags: ['comercial']

    marts:
      +schema: marts
      +materialized: table
      tags: ['marts']